name: PR Tests

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: 🧪 Test Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0

      - name: 🔧 Setup Dart SDK
        uses: dart-lang/setup-dart@v1.0

      - name: 🧪 Run Tests
        run: dart test
